<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="schedule" nsURI="http://mdse.org/pts/schedule" nsPrefix="schedule">
  <eClassifiers xsi:type="ecore:EClass" name="Schedule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="network" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="company" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trainSchedules" upperBound="-1"
        eType="#//TrainSchedule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrainSchedule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dateTimes" lowerBound="1"
        upperBound="-1" eType="#//DateTime" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="route" lowerBound="1" eType="#//Route"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateTime">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weekday" lowerBound="1"
        upperBound="-1" eType="#//WeekDays"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="time" lowerBound="1" eType="#//Time"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WeekDays">
    <eLiterals name="MONDAY" value="1"/>
    <eLiterals name="TUESDAY" value="2"/>
    <eLiterals name="WEDNESDAY" value="3"/>
    <eLiterals name="THURSDAY" value="4"/>
    <eLiterals name="FRIDAY" value="5"/>
    <eLiterals name="SATURDAY" value="6"/>
    <eLiterals name="SUNDAY" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Time">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hours" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minutes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Route">
    <eStructuralFeatures xsi:type="ecore:EReference" name="startSpot" lowerBound="1"
        eType="#//StartSpot" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="middleSpots" upperBound="-1"
        eType="#//MiddleSpot" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="finalSpot" lowerBound="1"
        eType="#//FinalSpot" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SituatedSpot" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="station" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="platform" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SituatedSpotWithConnection" abstract="true"
      eSuperTypes="#//SituatedSpot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leg" eType="ecore:EClass ../../org.mdse.pts.network/model/Network.ecore#//Leg"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StartSpot" eSuperTypes="#//SituatedSpotWithConnection"/>
  <eClassifiers xsi:type="ecore:EClass" name="MiddleSpot" eSuperTypes="#//SituatedSpotWithConnection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="waitingTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="turnStation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FinalSpot" eSuperTypes="#//SituatedSpot"/>
</ecore:EPackage>
