<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="schedule" nsURI="http://mdse.org/pts/schedule" nsPrefix="schedule">
  <eClassifiers xsi:type="ecore:EClass" name="Schedule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="network" lowerBound="1"
        eType="ecore:EClass ../../org.mdse.pts.network/model/Network.ecore#//Network"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="depots" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../org.mdse.pts.depot/model/Depot.ecore#//Depot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trainSchedules" upperBound="-1"
        eType="#//TrainSchedule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrainSchedule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="train" eType="ecore:EClass ../../org.mdse.pts.depot/model/Depot.ecore#//Train"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeDescription" lowerBound="1"
        eType="#//TimeDescription" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="route" lowerBound="1" eType="#//Route"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeDescription">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dateTimes" lowerBound="1"
        upperBound="-1" eType="#//DateTime" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateTime">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weekdays" lowerBound="1"
        upperBound="-1" eType="ecore:EEnum ../../org.mdse.pts.shared/model/Shared.ecore#//DaysOfTheWeek"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="time" lowerBound="1" eType="ecore:EClass ../../org.mdse.pts.shared/model/Shared.ecore#//Time"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Route">
    <eStructuralFeatures xsi:type="ecore:EReference" name="spots" lowerBound="2" upperBound="-1"
        eType="#//Spot" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Spot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="station" lowerBound="1"
        eType="ecore:EClass ../../org.mdse.pts.network/model/Network.ecore#//Station"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="platform" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="waitingTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="turnStation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leg" eType="ecore:EClass ../../org.mdse.pts.network/model/Network.ecore#//Leg"/>
  </eClassifiers>
</ecore:EPackage>
