<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="timetable" nsURI="http://mdse.org/pts/timetable" nsPrefix="timetable">
  <eClassifiers xsi:type="ecore:EClass" name="Timetable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stationTrains" upperBound="-1"
        eType="#//StationTrain"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stationName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StationTrain">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trainName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="departureTime" eType="#//DateTime"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arrivalTime" eType="#//DateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prevStation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nextStation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="platform" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateTime">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="day" eType="#//Days"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="time" eType="#//Time"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Days">
    <eLiterals name="Monday" value="1"/>
    <eLiterals name="Tuesday" value="2"/>
    <eLiterals name="Wednesday" value="3"/>
    <eLiterals name="Thursday" value="4"/>
    <eLiterals name="Friday" value="5"/>
    <eLiterals name="Saturday" value="6"/>
    <eLiterals name="Sunday" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Time">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hours" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minutes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
</ecore:EPackage>
